import Footer from '../../components/Footer'

export const metadata = { title: 'Legal Disclaimer — ContractAI' }

export default function DisclaimerPage() {
  return (
    <div>
      <div style={{ maxWidth: '680px', margin: '0 auto', padding: '56px 24px 24px' }}>
        <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '8px' }}>
          Last updated: June 2026
        </p>
        <h1 style={{ fontFamily: 'var(--serif)', fontSize: '32px', fontWeight: 600, marginBottom: '32px' }}>
          Legal Disclaimer
        </h1>

        <div style={{
          background: 'var(--red-bg)',
          border: '1px solid var(--red-border)',
          borderRadius: '10px',
          padding: '18px 22px',
          marginBottom: '32px',
        }}>
          <p style={{ fontSize: '14px', color: 'var(--red-text)', fontWeight: 500, lineHeight: 1.6, margin: 0 }}>
            ContractAI is not a law firm. Nothing generated by this product constitutes legal advice,
            and no attorney-client relationship is formed by using this service.
          </p>
        </div>

        <Section title="AI-generated analysis">
          ContractAI uses large language models (currently Google Gemini or Anthropic Claude) to
          analyse contract text and identify clauses that may carry risk. This analysis is generated
          automatically and is not reviewed by a licensed attorney before being shown to you.
        </Section>

        <Section title="No substitute for professional legal counsel">
          For contracts involving significant financial exposure, complex multi-party arrangements,
          regulatory matters, or anything you're unsure about, you should consult a qualified lawyer
          licensed in the relevant jurisdiction. ContractAI is designed to help you understand a
          contract faster and ask better questions — not to replace that judgment.
        </Section>

        <Section title="No guarantee of accuracy or completeness">
          AI models can misread context, miss nuance, or occasionally produce incorrect output. We
          do our best to tune the system for accuracy, but we cannot guarantee that every risky clause
          will be identified, or that every flag raised is correctly characterized.
        </Section>

        <Section title="Your responsibility">
          You remain solely responsible for any decision to sign, negotiate, or reject a contract.
          Use ContractAI's output as one input among several — not as the final word.
        </Section>

        <Section title="Jurisdictional differences">
          Contract law varies significantly between countries and even between states or regions
          within a country. ContractAI's analysis is general in nature and may not account for
          jurisdiction-specific rules that apply to your situation.
        </Section>
      </div>
      <Footer />
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: '28px' }}>
      <h2 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '8px', color: 'var(--text-primary)' }}>
        {title}
      </h2>
      <p style={{ fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.75 }}>
        {children}
      </p>
    </div>
  )
}
